language: node_js
dist: xenial
sudo: required

# ########################
# How to trigger a release
#
# Push a tag to origin:
# - "release" (= patch)
# - "release/patch"
# - "release/minor"
# - "release/major"
# ########################

stages:
  - name: build-test
    if: tag !~ /^release\/(major|minor|patch)$/
  - name: release
    if: tag =~ /^release\/(major|minor|patch)$/
    
jobs:
  include:
    - script: docker-compose build
      if: tag !~ ^release
    - stage: deploy
      if: tag =~ ^release
      script: skip
      deploy:
        provider: script
        script: npx @dappnode/dappnodesdk publish --dappnode_team_preset
        on:
          branch: master
